import { Red_Hat_Display } from "next/font/google";
import "./globals.css";

const geistSans = Red_Hat_Display({
  variable: "--font-geist-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
